name: DEV - Build

on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  APP_NAME: jame007-tutorial-frontend
  CONTAINER_REPOSITORY: "acrpattakorntutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

job:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: env
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
